import { Link } from "react-router";
import { ArrowRight, Check, Layout, Package, Zap } from "lucide-react";
import { AuroraBackground } from "~/components/aurora-background";

export default function Index() {
  return (
    <main className="relative min-h-screen overflow-x-hidden">
      <AuroraBackground />
      <header className="relative z-10 border-b border-border/40 bg-surface/30 backdrop-blur-xl"><div className="mx-auto flex max-w-7xl items-center justify-between px-6 py-4"><Link to="/" className="flex items-center gap-2 text-xl font-bold"><span className="text-gradient">Djumbai Shop</span></Link><div className="flex items-center gap-3"><Link to="/auth" className="rounded-xl px-3 py-2 text-sm font-semibold text-foreground/70 transition-colors hover:text-foreground">Entrar</Link><Link to="/auth?register=true" className="btn-glow rounded-xl bg-success px-3 py-2 text-sm font-semibold text-success-foreground">Criar loja</Link></div></div></header>
      <section className="relative z-10 hero-aura px-6 pb-20 pt-24"><div className="mx-auto max-w-7xl"><div className="grid items-center gap-12 lg:grid-cols-2"><div className="space-y-6"><span className="badge-aura inline-flex items-center gap-2 rounded-full px-3 py-1 text-xs font-medium text-primary"><Zap className="h-3.5 w-3.5" /> Catálogo pronto em minutos</span><h1 className="text-5xl font-bold leading-[1.1] tracking-tight md:text-6xl lg:text-7xl">Catálogos digitais com <span className="text-gradient">aura absoluta</span></h1><p className="max-w-lg text-lg text-muted-foreground">Cria um catálogo profissional para o teu negócio em minutos. Design impressionante, partilha instantânea e gestão simples.</p><div className="flex flex-wrap gap-4"><Link to="/auth?register=true" className="btn-glow inline-flex items-center justify-center gap-2 rounded-xl bg-success px-6 py-3.5 font-semibold text-success-foreground">Criar catálogo grátis<ArrowRight className="h-4 w-4" /></Link><Link to="/demo" className="inline-flex items-center justify-center gap-2 rounded-xl border border-border px-6 py-3.5 font-semibold transition-colors hover:bg-surface/40">Ver exemplo</Link></div></div><div className="glass-panel-strong motion-rise motion-delay-2 float-y relative rounded-3xl p-3 pulse-glow"><div className="aspect-[4/3] rounded-2xl bg-gradient-to-br from-primary/20 to-accent/20" /></div></div></div></div></section>
      <section className="relative z-10 px-6 py-20"><div className="mx-auto max-w-7xl"><div className="mb-12 text-center"><span className="badge-aura inline-flex rounded-full px-3 py-1 text-xs font-semibold text-primary">Demonstração · Exemplo de catálogo</span><h2 className="mt-4 text-3xl font-bold md:text-4xl">Produtos com <span className="text-gradient">presença</span></h2></div><div className="grid gap-6 sm:grid-cols-2 lg:grid-cols-3">{[1,2,3].map((i)=><article key={i} className="glass-panel group motion-rise surface-hover shine-sweep overflow-hidden rounded-2xl"><div className="aspect-[4/3] bg-gradient-to-br from-primary/10 to-accent/10"/><div className="p-5"><h3 className="font-semibold">Produto exemplo {i}</h3><p className="mt-1 text-sm text-muted-foreground">Descrição curta do produto.</p><div className="mt-4 flex items-center justify-between"><span className="text-lg font-bold">19.99€</span><button className="rounded-lg bg-primary px-4 py-1.5 text-sm font-semibold text-primary-foreground">Adicionar</button></div></div></article>)}</div><div className="mt-10 text-center"><Link to="/auth?register=true" className="btn-glow inline-flex items-center justify-center gap-2 rounded-xl bg-success px-6 py-3.5 font-semibold text-success-foreground">Criar a minha loja grátis<ArrowRight className="h-4 w-4" /></Link></div></div></section>
      <section className="relative z-10 px-6 py-20"><div className="mx-auto max-w-7xl"><div className="mb-12 text-center"><h2 className="text-3xl font-bold md:text-4xl">Tudo o que precisas num só lugar</h2></div><div className="grid gap-6 md:grid-cols-3">{[{icon:Layout,title:"Design impressionante",desc:"Templates com glass, neon e animações que captam atenção."},{icon:Package,title:"Gestão simples",desc:"Adiciona, edita e organiza os teus produtos facilmente."},{icon:Check,title:"Partilha instantânea",desc:"Link público para partilhar com clientes em segundos."}].map((benefit,i)=><div key={i} className="glass-panel motion-rise surface-hover shine-sweep rounded-2xl p-6"><benefit.icon className="h-8 w-8 text-primary"/><h3 className="mt-4 text-xl font-semibold">{benefit.title}</h3><p className="mt-2 text-muted-foreground">{benefit.desc}</p></div>)}</div></div></section>
      <section className="relative z-10 px-6 py-20"><div className="mx-auto max-w-7xl"><div className="mb-12 text-center"><h2 className="text-3xl font-bold md:text-4xl">Começa em <span className="text-gradient">3 passos</span></h2></div><div className="grid gap-6 md:grid-cols-3">{[{step:"1",title:"Cria conta",desc:"Regista-te grátis em segundos."},{step:"2",title:"Adiciona produtos",desc:"Preenche os detalhes do teu catálogo."},{step:"3",title:"Partilha",desc:"Partilha o link com os teus clientes."}].map((step,i)=><div key={i} className="glass-panel surface-hover rounded-2xl p-6"><div className="flex h-12 w-12 items-center justify-center rounded-full bg-primary/20 text-2xl font-bold text-primary">{step.step}</div><h3 className="mt-4 text-xl font-semibold">{step.title}</h3><p className="mt-2 text-muted-foreground">{step.desc}</p></div>)}</div></div></section>
      <section className="relative z-10 px-6 py-20"><div className="mx-auto max-w-7xl"><div className="mb-12 text-center"><h2 className="text-3xl font-bold md:text-4xl">Planos <span className="text-gradient">flexíveis</span></h2></div><div className="grid gap-6 md:grid-cols-3">{[{name:"Grátis",price:"0€",highlight:false,features:["Até 10 produtos","Link público","Suporte básico"]},{name:"Pro",price:"9.99€",highlight:true,features:["Produtos ilimitados","Design premium","Suporte prioritário"]},{name:"Empresa",price:"24.99€",highlight:false,features:["Tudo do Pro","Múltiplas lojas","API e integrações"]}].map((plan,i)=><article key={i} className={`surface-hover shine-sweep rounded-3xl p-7 ${plan.highlight?"glass-panel-strong glow-ring-strong border-primary/40":"border border-border bg-surface/40"}`}><h3 className="text-xl font-bold">{plan.name}</h3><p className="mt-2 text-3xl font-bold">{plan.price}</p><p className="text-sm text-muted-foreground">por mês</p><ul className="mt-6 space-y-2">{plan.features.map((feature,j)=><li key={j} className="flex items-center gap-2 text-sm"><Check className="h-4 w-4 text-success"/>{feature}</li>)}</ul><Link to="/auth?register=true" className={plan.highlight?"btn-glow mt-7 inline-flex w-full items-center justify-center rounded-xl bg-success px-5 py-3 font-semibold text-success-foreground":"mt-7 inline-flex w-full items-center justify-center rounded-xl border border-border bg-secondary/60 px-5 py-3 font-semibold text-foreground transition-transform hover:scale-[1.02] active:scale-100"}>Começar</Link></article>)}</div></div></section>
      <section className="relative z-10 px-6 py-20"><div className="glass-panel-strong glow-ring-strong pulse-glow mx-auto max-w-4xl rounded-3xl p-9 text-center"><h2 className="text-3xl font-bold md:text-4xl">Publica o teu catálogo hoje</h2><p className="mx-auto mt-3 max-w-lg text-muted-foreground">Junta-te a centenas de negócios que já usam a Djumbai Shop.</p><Link to="/auth?register=true" className="btn-glow mt-7 inline-flex items-center justify-center gap-2 rounded-xl bg-success px-7 py-3.5 font-semibold text-success-foreground">Criar loja grátis<ArrowRight className="h-4 w-4" /></Link></div></section>
      <div className="noise-overlay" aria-hidden="true" />
    </main>
  );
}
